/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ComponentOne {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface ComponentOneAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ComponentOne': Components.ComponentOne;
  }

  interface StencilIntrinsicElements {
    'component-one': Components.ComponentOneAttributes;
  }


  interface HTMLComponentOneElement extends Components.ComponentOne, HTMLStencilElement {}
  var HTMLComponentOneElement: {
    prototype: HTMLComponentOneElement;
    new (): HTMLComponentOneElement;
  };

  interface HTMLElementTagNameMap {
    'component-one': HTMLComponentOneElement
  }

  interface ElementTagNameMap {
    'component-one': HTMLComponentOneElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
